### ISSUE TITLE
404s in Safari

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-actionable-text-icons-design#2]
Getting lots of 404s in Safari, but no other browsers. Everything looks and works as expected.

![safari9_specials](https://cloud.githubusercontent.com/assets/9092541/26431659/2157506c-40ab-11e7-8446-62e828e0327b.png)

**Comment by randyaskin** [comment]
With release of Safari 11 last month, we only need to support Safari 10 & 11.
